# Generated by Django 3.0.7 on 2024-02-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240127_1140'),
        ('accounts', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='own',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
    ]
