# Generated by Django 3.0.7 on 2024-02-06 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
