# Generated by Django 3.0.7 on 2024-02-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seler',
        ),
    ]
