# Generated by Django 3.0.7 on 2024-02-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20240206_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
